"""UI components for G-Account Manager."""

from .icons import (
    create_color_icon,
    create_custom_color_icon,
    create_arrow_icon,
    create_list_icon,
    create_folder_icon,
    create_trash_icon,
    create_plus_icon,
    create_import_icon,
    create_clear_icon,
    create_close_icon,
    create_check_icon,
    create_minus_icon,
    create_restore_icon,
    create_lock_icon,
    create_edit_icon,
    create_clock_icon,
    get_pastel_color,
)

__all__ = [
    "create_color_icon",
    "create_custom_color_icon",
    "create_arrow_icon",
    "create_list_icon",
    "create_folder_icon",
    "create_trash_icon",
    "create_plus_icon",
    "create_import_icon",
    "create_clear_icon",
    "create_close_icon",
    "create_check_icon",
    "create_minus_icon",
    "create_restore_icon",
    "create_lock_icon",
    "create_edit_icon",
    "create_clock_icon",
    "get_pastel_color",
]
